name: 部署文件到服务器
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false


    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Server
      uses: lexmin0412/ssh-deploy@master
      with: # 以下为参数
        USERNAME: ${{ secrets.DEPLOY_USER }}
        PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
        HOST: ${{ secrets.DEPLOY_HOST }}
        SOURCE: build,public
        TARGET: /cellerchan.top/remix-blog-manager/build,/cellerchan.top/remix-blog-manager/public
